/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.boxalino.dataintelligence.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * This structure defines a map key (signature) of a behavior report result (indication about what this result is about)
 * The BehaviorReport object contains a map with the results. For each key (i.e.: result group) the system returns a list of report metrics (kpis) and value for each date range requested.
 * These keys are, in the case of a BehaviorReport defined by a map of dimension values for each requested Dimension
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-1-14")
public class BehaviorReportResult implements org.apache.thrift.TBase<BehaviorReportResult, BehaviorReportResult._Fields>, java.io.Serializable, Cloneable, Comparable<BehaviorReportResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BehaviorReportResult");

  private static final org.apache.thrift.protocol.TField DIMENSION_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("dimensionValue", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BehaviorReportResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BehaviorReportResultTupleSchemeFactory());
  }

  /**
   * an required map of dimension values
   */
  public Map<ReportDimension,String> dimensionValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * an required map of dimension values
     */
    DIMENSION_VALUE((short)1, "dimensionValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DIMENSION_VALUE
          return DIMENSION_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DIMENSION_VALUE, new org.apache.thrift.meta_data.FieldMetaData("dimensionValue", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ReportDimension.class), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BehaviorReportResult.class, metaDataMap);
  }

  public BehaviorReportResult() {
  }

  public BehaviorReportResult(
    Map<ReportDimension,String> dimensionValue)
  {
    this();
    this.dimensionValue = dimensionValue;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BehaviorReportResult(BehaviorReportResult other) {
    if (other.isSetDimensionValue()) {
      Map<ReportDimension,String> __this__dimensionValue = new HashMap<ReportDimension,String>(other.dimensionValue.size());
      for (Map.Entry<ReportDimension, String> other_element : other.dimensionValue.entrySet()) {

        ReportDimension other_element_key = other_element.getKey();
        String other_element_value = other_element.getValue();

        ReportDimension __this__dimensionValue_copy_key = new ReportDimension(other_element_key);

        String __this__dimensionValue_copy_value = other_element_value;

        __this__dimensionValue.put(__this__dimensionValue_copy_key, __this__dimensionValue_copy_value);
      }
      this.dimensionValue = __this__dimensionValue;
    }
  }

  public BehaviorReportResult deepCopy() {
    return new BehaviorReportResult(this);
  }

  @Override
  public void clear() {
    this.dimensionValue = null;
  }

  public int getDimensionValueSize() {
    return (this.dimensionValue == null) ? 0 : this.dimensionValue.size();
  }

  public void putToDimensionValue(ReportDimension key, String val) {
    if (this.dimensionValue == null) {
      this.dimensionValue = new HashMap<ReportDimension,String>();
    }
    this.dimensionValue.put(key, val);
  }

  /**
   * an required map of dimension values
   */
  public Map<ReportDimension,String> getDimensionValue() {
    return this.dimensionValue;
  }

  /**
   * an required map of dimension values
   */
  public BehaviorReportResult setDimensionValue(Map<ReportDimension,String> dimensionValue) {
    this.dimensionValue = dimensionValue;
    return this;
  }

  public void unsetDimensionValue() {
    this.dimensionValue = null;
  }

  /** Returns true if field dimensionValue is set (has been assigned a value) and false otherwise */
  public boolean isSetDimensionValue() {
    return this.dimensionValue != null;
  }

  public void setDimensionValueIsSet(boolean value) {
    if (!value) {
      this.dimensionValue = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DIMENSION_VALUE:
      if (value == null) {
        unsetDimensionValue();
      } else {
        setDimensionValue((Map<ReportDimension,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DIMENSION_VALUE:
      return getDimensionValue();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DIMENSION_VALUE:
      return isSetDimensionValue();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BehaviorReportResult)
      return this.equals((BehaviorReportResult)that);
    return false;
  }

  public boolean equals(BehaviorReportResult that) {
    if (that == null)
      return false;

    boolean this_present_dimensionValue = true && this.isSetDimensionValue();
    boolean that_present_dimensionValue = true && that.isSetDimensionValue();
    if (this_present_dimensionValue || that_present_dimensionValue) {
      if (!(this_present_dimensionValue && that_present_dimensionValue))
        return false;
      if (!this.dimensionValue.equals(that.dimensionValue))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_dimensionValue = true && (isSetDimensionValue());
    list.add(present_dimensionValue);
    if (present_dimensionValue)
      list.add(dimensionValue);

    return list.hashCode();
  }

  @Override
  public int compareTo(BehaviorReportResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDimensionValue()).compareTo(other.isSetDimensionValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDimensionValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dimensionValue, other.dimensionValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BehaviorReportResult(");
    boolean first = true;

    sb.append("dimensionValue:");
    if (this.dimensionValue == null) {
      sb.append("null");
    } else {
      sb.append(this.dimensionValue);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (dimensionValue == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dimensionValue' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BehaviorReportResultStandardSchemeFactory implements SchemeFactory {
    public BehaviorReportResultStandardScheme getScheme() {
      return new BehaviorReportResultStandardScheme();
    }
  }

  private static class BehaviorReportResultStandardScheme extends StandardScheme<BehaviorReportResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BehaviorReportResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DIMENSION_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map286 = iprot.readMapBegin();
                struct.dimensionValue = new HashMap<ReportDimension,String>(2*_map286.size);
                ReportDimension _key287;
                String _val288;
                for (int _i289 = 0; _i289 < _map286.size; ++_i289)
                {
                  _key287 = new ReportDimension();
                  _key287.read(iprot);
                  _val288 = iprot.readString();
                  struct.dimensionValue.put(_key287, _val288);
                }
                iprot.readMapEnd();
              }
              struct.setDimensionValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BehaviorReportResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dimensionValue != null) {
        oprot.writeFieldBegin(DIMENSION_VALUE_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRUCT, org.apache.thrift.protocol.TType.STRING, struct.dimensionValue.size()));
          for (Map.Entry<ReportDimension, String> _iter290 : struct.dimensionValue.entrySet())
          {
            _iter290.getKey().write(oprot);
            oprot.writeString(_iter290.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BehaviorReportResultTupleSchemeFactory implements SchemeFactory {
    public BehaviorReportResultTupleScheme getScheme() {
      return new BehaviorReportResultTupleScheme();
    }
  }

  private static class BehaviorReportResultTupleScheme extends TupleScheme<BehaviorReportResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BehaviorReportResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.dimensionValue.size());
        for (Map.Entry<ReportDimension, String> _iter291 : struct.dimensionValue.entrySet())
        {
          _iter291.getKey().write(oprot);
          oprot.writeString(_iter291.getValue());
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BehaviorReportResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TMap _map292 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRUCT, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.dimensionValue = new HashMap<ReportDimension,String>(2*_map292.size);
        ReportDimension _key293;
        String _val294;
        for (int _i295 = 0; _i295 < _map292.size; ++_i295)
        {
          _key293 = new ReportDimension();
          _key293.read(iprot);
          _val294 = iprot.readString();
          struct.dimensionValue.put(_key293, _val294);
        }
      }
      struct.setDimensionValueIsSet(true);
    }
  }

}

