/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.boxalino.dataintelligence.api.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * This enumeration defines possible types of columns which can be used in a reference CSV file
 */
public enum CSVFileColumnType implements org.apache.thrift.TEnum {
  /**
   * text string encoded using UTF-8 encoding
   */
  STRING(1),
  /**
   * signed 64-bit integer
   */
  INTEGER(2),
  /**
   * floating point number
   */
  DOUBLE(3),
  /**
   * textual representation of the date and time in the format YYYY-MM-DD HH:MM:SS
   */
  DATETIME(4),
  /**
   * textual representation of the date in the format YYYY-MM-DD
   */
  DATE(5),
  /**
   * textual representation of the time in the format HH:MM:SS
   */
  TIME(6),
  /**
   * numerical representation of the date and time as an unsigned 32-bit integer, counting the seconds since the start of the UNIX epoch
   */
  UNIX_TIMESTAMP(7);

  private final int value;

  private CSVFileColumnType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CSVFileColumnType findByValue(int value) { 
    switch (value) {
      case 1:
        return STRING;
      case 2:
        return INTEGER;
      case 3:
        return DOUBLE;
      case 4:
        return DATETIME;
      case 5:
        return DATE;
      case 6:
        return TIME;
      case 7:
        return UNIX_TIMESTAMP;
      default:
        return null;
    }
  }
}
